### ISSUE TITLE
False failures when comparing status codes

### ISSUE THREAD

**Issue by tigerw** [FlexyProject/Curl#1]
To determine if a failure has occurred, Client compares the returned status code with `200 (OK)`. However, with GitHub, at least one other is returned; `201 (Created)` for [creating a repository web hook](https://developer.github.com/v3/repos/hooks/#create-a-hook), which unexpectedly triggers an error when the request was successful.

Perhaps a workable solution would be to compare to the range [100, 299] for "informational" and "successful" statuses, or [100, 399] for the previous two plus "redirection", to determine if the status code was not in the [400, 599] error range.

**Comment by emulienfou** [comment]
Fixed, thanks for your help!

**Comment by tigerw** [comment]
:)
